version: '3'

services:
  my-app:
    image: openjdk:8-jre-alpine
    container_name: my-app-container
    volumes:
      - ./target/task-demo-metrics-prometheus-2.0.1-SNAPSHOT.jar:/app/task-demo-metrics-prometheus-2.0.1-SNAPSHOT.jar
    command: ["java", "-jar", "/app/task-demo-metrics-prometheus-2.0.1-SNAPSHOT.jar"]
    ports:
      - "8080:8080"

  nginx:
    image: nginx
    container_name: nginx-container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./target/task-demo-metrics-prometheus-2.0.1-SNAPSHOT.jar:/usr/share/nginx/html/task-demo-metrics-prometheus-2.0.1-SNAPSHOT.jar
    ports:
      - "80:80"
